dist: xenial
language: python
sudo: false
python:
#    - "2.6" removed because tests aren't 2.6-compatible
    - "2.7"
#    - "3.2" removed because Coveralls/coverage 4.0 fails on 3.2
#    - "3.3" removed because fails on Travis with Xenial
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy2.7-6.0"
    - "pypy3.5-6.0"
install:
    - pip install coveralls
script:
    - "NO_EXTERNAL_TESTS=1 python test_gnupg.py --no-doctests"
    - "NO_EXTERNAL_TESTS=1 coverage run test_gnupg.py --no-doctests"
after_success: coveralls
