version: 1.0.{build}
image:
  - Visual Studio 2017
  - ubuntu1804
  - macos
  - macos-mojave
environment:
  NO_EXTERNAL_TESTS: 1
  matrix:
  - TOXENV: py27
#  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38
#  - TOXENV: py39

for:
-
  matrix:
    only:
      - image: Visual Studio 2017

  install:
  - ps: |
          $path = [Environment]::GetEnvironmentVariable("path", "machine")
          $origPath = $path
          $newPath = ($path.Split(';') | Where-Object { $_ -eq 'C:\ProgramData\chocolatey\bin' }) -join ';'
          [Environment]::SetEnvironmentVariable("path", $newPath, "machine")
          refreshenv
          appveyor-retry choco install gnupg
          $newPath = "C:\Program Files (x86)\GnuPG\bin;" + $origPath
          [Environment]::SetEnvironmentVariable("path", $newPath, "machine")
          refreshenv
          Write-Host $newPath
          cmd /r "C:\Program Files (x86)\GnuPG\bin\gpg.exe" --version

  - cmd: pip install tox

install:
- cmd: pip install tox
build: off
test_script:
- cmd: tox -c av-tox.ini
on_failure:
- cmd: type test_gnupg.log

