name: automate.yml

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

    branches:       #[ master ]
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - 'master'    # includes master
      - 'main'      # includes main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  printenv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
        exclude:
          - os: ubuntu-latest
            python-version: ['2.7','3.6','3.7','3.8','3.10']
          - os: macos-latest
            python-version: ['2.7','3.6','3.7','3.8','3.10']
          - os: macos-10.15
            python-version: ['2.7','3.6','3.7','3.8','3.10']
          - os: m1.local
            python-version: ['2.7','3.6','3.7','3.8','3.10']
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Matrix
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Print github workspace
        run: |
          printenv
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          python3 -c "import sys; print(sys.version)"
          make init
          make seeder

  automate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9','3.8','3.7']
        exclude:
          - os: ubuntu-latest
            python-version: ['2.7','3.6','3.7','3.8','3.10']
          - os: macos-latest
            python-version: ['2.7','3.6','3.7','3.8','3.10']
          - os: macos-10.15
            python-version: ['2.7','3.6','3.7','3.8','3.10']
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Matrix
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: automate.sh matrix
        run: |
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          python3 -c "import sys; print(sys.version)"
          make init
          make seeder

