name: virtualenv

on: [push]

jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  linter:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
    - run: make init
    - run: flake8
      #- run: pydocstyle
      #- run: isort . --skip 0x20bf/p2p --skip 0x20bf/gnupg/
      #- run: echo "0x20bf/p2p"   >> .gitignore
      #- run: echo "0x20bf/gnupg" >> .gitignore
      #- run: black 0x20bf
    - run: isort 0x20bf
    - run: black 0x20bf

  tests:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - run: ./tests/py.test